/**
 * Canvas 2D force-directed graph visualization for the dashboard.
 *
 * Lightweight alternative to D3/vis.js — ~180 lines of vanilla JS,
 * handles up to ~500 nodes at 60fps.
 *
 * Physics:
 *   - Pairwise repulsion (Coulomb-like) pushes unconnected nodes apart
 *   - Spring attraction along each edge pulls connected nodes together
 *   - Velocity damping provides settling behavior (no explicit cooling)
 *
 * Interaction:
 *   - Drag canvas to pan
 *   - Scroll to zoom (anchored on cursor)
 *   - Click a node to highlight (god nodes are pre-emphasized)
 */

export function buildGraphScript(): string {
  return [
    "// \u2500\u2500\u2500 Global graph stop handle (ensures re-rendering doesn't leak loops) \u2500\u2500\u2500",
    "window.__engram_graph_stop = window.__engram_graph_stop || null;",
    "",
    "// \u2500\u2500\u2500 Node color by kind (match the graph schema) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
    "const NODE_COLORS = {",
    "  file: \"#3b82f6\",",
    "  function: \"#10b981\",",
    "  class: \"#a855f7\",",
    "  concept: \"#f59e0b\",",
    "  mistake: \"#ef4444\",",
    "  decision: \"#eab308\",",
    "  default: \"#71717a\",",
    "};",
    "",
    "// Memory scope mapping: color + shape + label. These represent the three",
    "// memory types we care about: project, global, and personal/entity.",
    "const MEMORY_SCOPE_CONFIG = {",
    "  project: { color: \"#3b82f6\", shape: \"circle\", label: \"Project\" },",
    "  global: { color: \"#a855f7\", shape: \"diamond\", label: \"Global\" },",
    "  entity: { color: \"#f59e0b\", shape: \"square\", label: \"Personal\" },",
    "  default: { color: \"#71717a\", shape: \"circle\", label: \"Unknown\" },",
    "};",
    "",
    "// Visual consolidation & distribution knobs",
    "const TOTAL_VISUAL_BUDGET = 200;    // combined visual budget baseline (nodes + edges)",
    "const NODE_PROP = 2 / 3;            // fraction of budget aimed at nodes",
    "const EDGE_PROP = 1 - NODE_PROP;    // fraction for edges",
    "const SCOPE_RATIOS = { project: 0.5, global: 0.25, entity: 0.25 };",
    "const MINORITY_THRESHOLD = 0.05;    // scopes under 5% are treated as \"minorities\" and preserved",
    "",
    "// Obsidian-style shells: project core \u2192 god hubs \u2192 child nodes \u2192 edge/leaves.",
    "const NODE_SHELLS = {",
    "  project: { radius: 34, alpha: 1.0, size: 8.6, pull: 0.08 },",
    "  god: { radius: 82, alpha: 0.95, size: 7.0, pull: 0.05 },",
    "  child: { radius: 124, alpha: 0.82, size: 5.4, pull: 0.03 },",
    "  edge: { radius: 170, alpha: 0.68, size: 4.4, pull: 0.018 },",
    "};",
    "const PROJECT_NODE_KINDS = new Set([\"file\", \"module\"]);",
    "",
    "function hashString(value) {",
    "  let hash = 2166136261;",
    "  for (let i = 0; i < value.length; i++) {",
    "    hash ^= value.charCodeAt(i);",
    "    hash = Math.imul(hash, 16777619);",
    "  }",
    "  return hash >>> 0;",
    "}",
    "",
    "function stableAngle(id, seed = \"\") {",
    "  const hash = hashString(`${id}|${seed}`);",
    "  return (hash / 4294967295) * Math.PI * 2;",
    "}",
    "",
    "const PROJECT_FILL_PALETTE = [\"#3b82f6\", \"#06b6d4\", \"#22c55e\", \"#f59e0b\", \"#a855f7\", \"#ef4444\", \"#14b8a6\", \"#e879f9\"];",
    "const SCOPE_OUTLINE_COLORS = {",
    "  project: \"#60a5fa\",",
    "  global: \"#c084fc\",",
    "  entity: \"#f59e0b\",",
    "  default: \"#94a3b8\",",
    "};",
    "",
    "function seededNoise(seed) {",
    "  return (hashString(seed) % 10000) / 10000;",
    "}",
    "",
    "function escHtml(value) {",
    "  if (value === null || value === undefined) return \"\";",
    "  return String(value)",
    "    .replaceAll(\"&\", \"&amp;\")",
    "    .replaceAll(\"<\", \"&lt;\")",
    "    .replaceAll(\">\", \"&gt;\")",
    "    .replaceAll(\"\\\"\", \"&quot;\")",
    "    .replaceAll(\"'\", \"&#39;\");",
    "}",
    "",
    "function projectFillColor(root) {",
    "  return PROJECT_FILL_PALETTE[hashString(root || \"__no_project__\") % PROJECT_FILL_PALETTE.length];",
    "}",
    "",
    "function scopeOutlineColor(scope) {",
    "  return SCOPE_OUTLINE_COLORS[scope] || SCOPE_OUTLINE_COLORS.default;",
    "}",
    "",
    "function tierShape(tier) {",
    "  return tier === \"edge\" ? \"diamond\" : \"circle\";",
    "}",
    "",
    "function visualNodeRadius(tier, degree = 0) {",
    "  const shell = NODE_SHELLS[tier] || NODE_SHELLS.edge;",
    "  const degreeBoost = Math.min(3.5, degree * 0.18);",
    "  const tierBoost = tier === \"project\" ? 2.1 : tier === \"god\" ? 1.4 : tier === \"child\" ? 0.5 : 0;",
    "  return shell.size + degreeBoost + tierBoost;",
    "}",
    "",
    "function pathShape(ctx, x, y, r, shape) {",
    "  ctx.beginPath();",
    "  if (shape === \"circle\") {",
    "    ctx.arc(x, y, r, 0, Math.PI * 2);",
    "  } else if (shape === \"square\") {",
    "    ctx.rect(x - r, y - r, r * 2, r * 2);",
    "  } else if (shape === \"diamond\") {",
    "    ctx.moveTo(x, y - r);",
    "    ctx.lineTo(x + r, y);",
    "    ctx.lineTo(x, y + r);",
    "    ctx.lineTo(x - r, y);",
    "    ctx.closePath();",
    "  } else {",
    "    // fallback to circle",
    "    ctx.arc(x, y, r, 0, Math.PI * 2);",
    "  }",
    "}",
    "",
    "/**",
    " * Main entry point. Given a canvas element and node/edge data from",
    " * /api/graph/nodes and /api/graph/god-nodes, starts the simulation.",
    " */",
    "function renderGraph(canvas, nodes, godNodes, edges) {",
    "  // Stop any previous running simulation to avoid animation/handler leaks",
    "  if (typeof window.__engram_graph_stop === 'function') {",
    "    try { window.__engram_graph_stop(); } catch {}",
    "    window.__engram_graph_stop = null;",
    "  }",
    "  const ctx = canvas.getContext(\"2d\");",
    "  const rect = canvas.getBoundingClientRect();",
    "  canvas.width = rect.width * window.devicePixelRatio;",
    "  canvas.height = rect.height * window.devicePixelRatio;",
    "  ctx.scale(window.devicePixelRatio, window.devicePixelRatio);",
    "",
    "  const W = rect.width;",
    "  const H = rect.height;",
    "  const persistedView = window.__engram_graph_viewState || {};",
    "  const layoutMode = String(window.__engram_graph_layoutMode || \"settle-first\");",
    "  const autoFitView = layoutMode === \"stream\" || window.__engram_graph_autoFit === true;",
    "  const layoutScale = Math.max(1, Number(window.__engram_graph_layoutScale || 1));",
    "  const perfNow = typeof performance !== 'undefined' && typeof performance.now === 'function' ? () => performance.now() : () => Date.now();",
    "  const totalStart = perfNow();",
    "  const layoutState = window.__engram_graph_layoutState || (window.__engram_graph_layoutState = { positions: new Map(), seenIds: new Set(), perf: { sampleCount: 0, avgTotalMs: 0, avgLayoutMs: 0, maxTotalMs: 0, maxLayoutMs: 0, slowFrames: 0, lastNodeCount: 0, lastEdgeCount: 0 } });",
    "  const perfState = layoutState.perf;",
    "  const priorPositions = layoutState.positions || new Map();",
    "  let layoutDuration = 0;",
    "  let perfRecorded = false;",
    "",
    "  // God node IDs (for emphasis). godNodes shape: [{node, degree}]",
    "  const godIds = new Set((godNodes || []).map((g) => g.node?.id).filter(Boolean));",
    "",
    "  // Build simulation nodes with random starting positions near center.",
    "  // Default memoryScope to 'project' when missing so code files show as",
    "  // project-scope nodes by default.",
    "",
    "  // Build a map of nodes (include placeholders for any edge endpoints",
    "  // that the server didn't return). This ensures springs can be wired",
    "  // even when the node list is paginated or truncated.",
    "  const baseNodes = Array.isArray(nodes) ? nodes.slice() : [];",
    "  const nodeMapAll = new Map();",
    "  for (const n of baseNodes) nodeMapAll.set(n.id, n);",
    "",
    "  // Compute degree map from provided edges so we can bias placement",
    "  const degreeMap = new Map();",
    "  if (Array.isArray(edges)) {",
    "    for (const ed of edges) {",
    "      degreeMap.set(ed.source, (degreeMap.get(ed.source) || 0) + 1);",
    "      degreeMap.set(ed.target, (degreeMap.get(ed.target) || 0) + 1);",
    "      if (!nodeMapAll.has(ed.source)) {",
    "        nodeMapAll.set(ed.source, { id: ed.source, label: ed.source, kind: 'default', metadata: {} });",
    "      }",
    "      if (!nodeMapAll.has(ed.target)) {",
    "        nodeMapAll.set(ed.target, { id: ed.target, label: ed.target, kind: 'default', metadata: {} });",
    "      }",
    "    }",
    "  }",
    "",
    "  // Consolidation helper: choose a subset of nodes/edges to render that",
    "  // respects a global visual budget, scope distribution, and minority",
    "  // preservation.",
    "  function consolidateNodesAndEdges(allNodesArr, allEdgesArr, godIdsSet) {",
    "    const totalAvailable = allNodesArr.length;",
    "    const nodesBudget = Math.max(10, Math.floor(TOTAL_VISUAL_BUDGET * NODE_PROP));",
    "    const edgesBudget = Math.max(5, TOTAL_VISUAL_BUDGET - nodesBudget);",
    "",
    "    // If the data is already small, return fast",
    "    if (totalAvailable <= nodesBudget) {",
    "      const keptNodes = allNodesArr.slice();",
    "      const keptNodeIds = new Set(keptNodes.map(n => n.id));",
    "      let keptEdges = (Array.isArray(allEdgesArr) ? allEdgesArr.slice() : []).filter(e => keptNodeIds.has(e.source) && keptNodeIds.has(e.target));",
    "      // score & trim edges if needed",
    "      if (keptEdges.length > edgesBudget) {",
    "        keptEdges.sort((a, b) => edgeScore(b) - edgeScore(a));",
    "        keptEdges = keptEdges.slice(0, edgesBudget);",
    "      }",
    "      return { nodes: keptNodes, edges: keptEdges };",
    "    }",
    "",
    "    // Bucket nodes by memory scope",
    "    const buckets = { project: [], global: [], entity: [] };",
    "    for (const n of allNodesArr) {",
    "      try {",
    "        const meta = n.metadata || {};",
    "        const ms = (meta.memoryScope || meta.memory_scope) || 'project';",
    "        if (ms === 'global') buckets.global.push(n);",
    "        else if (ms === 'entity' || ms === 'personal') buckets.entity.push(n);",
    "        else buckets.project.push(n);",
    "      } catch {",
    "        buckets.project.push(n);",
    "      }",
    "    }",
    "",
    "    // initial allocation by configured ratios",
    "    const initialAlloc = {",
    "      project: Math.floor(nodesBudget * SCOPE_RATIOS.project),",
    "      global: Math.floor(nodesBudget * SCOPE_RATIOS.global),",
    "      entity: Math.floor(nodesBudget * SCOPE_RATIOS.entity),",
    "    };",
    "",
    "    const minMinorityCount = Math.max(1, Math.floor(totalAvailable * MINORITY_THRESHOLD));",
    "",
    "    const alloc = { project: 0, global: 0, entity: 0 };",
    "    for (const k of Object.keys(initialAlloc)) {",
    "      const avail = buckets[k].length;",
    "      if (avail <= initialAlloc[k] || avail <= minMinorityCount) {",
    "        alloc[k] = avail; // preserve small groups entirely",
    "      } else {",
    "        alloc[k] = initialAlloc[k];",
    "      }",
    "    }",
    "",
    "    // Redistribute any remaining budget to scopes that still need nodes",
    "    let remaining = nodesBudget - (alloc.project + alloc.global + alloc.entity);",
    "    while (remaining > 0) {",
    "      const needs = {",
    "        project: Math.max(0, buckets.project.length - alloc.project),",
    "        global: Math.max(0, buckets.global.length - alloc.global),",
    "        entity: Math.max(0, buckets.entity.length - alloc.entity),",
    "      };",
    "      const totalNeed = needs.project + needs.global + needs.entity;",
    "      if (totalNeed === 0) break;",
    "      let assigned = 0;",
    "      for (const k of ['project', 'global', 'entity']) {",
    "        if (needs[k] <= 0) continue;",
    "        const extra = Math.max(1, Math.floor(remaining * (needs[k] / totalNeed)));",
    "        const give = Math.min(extra, needs[k]);",
    "        alloc[k] += give;",
    "        assigned += give;",
    "      }",
    "      if (assigned === 0) {",
    "        // fallback: assign one-by-one round-robin",
    "        for (const k of ['project', 'global', 'entity']) {",
    "          if (alloc[k] < buckets[k].length && remaining > 0) { alloc[k]++; remaining--; }",
    "        }",
    "        break;",
    "      }",
    "      remaining -= assigned;",
    "    }",
    "",
    "    // Score function for nodes: prefer god nodes and higher degree",
    "    function nodeScore(n) {",
    "      const deg = degreeMap.get(n.id) || 0;",
    "      const godBoost = godIdsSet && godIdsSet.has(n.id) ? 2000 : 0;",
    "      return godBoost + deg;",
    "    }",
    "",
    "    // Pick top nodes per bucket by nodeScore",
    "    const keptNodes = [];",
    "    for (const k of ['project', 'global', 'entity']) {",
    "      const arr = buckets[k].slice();",
    "      arr.sort((a, b) => nodeScore(b) - nodeScore(a));",
    "      const take = Math.min(arr.length, alloc[k]);",
    "      for (let i = 0; i < take; i++) keptNodes.push(arr[i]);",
    "    }",
    "",
    "    // If we still have leftover slots (due to rounding), fill with highest-scoring remaining nodes",
    "    if (keptNodes.length < nodesBudget) {",
    "      const keptIds = new Set(keptNodes.map(n => n.id));",
    "      const rem = allNodesArr.filter(n => !keptIds.has(n.id));",
    "      rem.sort((a, b) => nodeScore(b) - nodeScore(a));",
    "      for (let i = 0; i < Math.min(rem.length, nodesBudget - keptNodes.length); i++) keptNodes.push(rem[i]);",
    "    }",
    "",
    "    const keptNodeIds = new Set(keptNodes.map(n => n.id));",
    "",
    "    // Edge score: prefer edges between high-degree nodes, god-involving edges, and keep minority-scope edges slightly boosted",
    "    function edgeScore(e) {",
    "      const sDeg = degreeMap.get(e.source) || 0;",
    "      const tDeg = degreeMap.get(e.target) || 0;",
    "      const godBoost = (godIdsSet && (godIdsSet.has(e.source) || godIdsSet.has(e.target))) ? 200 : 0;",
    "      let scopeBoost = 0;",
    "      try {",
    "        const sScope = (nodeMapAll.get(e.source) && ((nodeMapAll.get(e.source).metadata && (nodeMapAll.get(e.source).metadata.memoryScope || nodeMapAll.get(e.source).metadata.memory_scope)))) || 'project';",
    "        const tScope = (nodeMapAll.get(e.target) && ((nodeMapAll.get(e.target).metadata && (nodeMapAll.get(e.target).metadata.memoryScope || nodeMapAll.get(e.target).metadata.memory_scope)))) || 'project';",
    "        const total = allNodesArr.length || 1;",
    "        // If either endpoint belongs to a small/minority scope, slightly boost the edge",
    "        if ((sScope === 'global' && buckets.global.length / total < MINORITY_THRESHOLD) ||",
    "            (tScope === 'global' && buckets.global.length / total < MINORITY_THRESHOLD) ||",
    "            (sScope === 'entity' && buckets.entity.length / total < MINORITY_THRESHOLD) ||",
    "            (tScope === 'entity' && buckets.entity.length / total < MINORITY_THRESHOLD)) {",
    "          scopeBoost = 20;",
    "        }",
    "      } catch (ex) {}",
    "      return sDeg + tDeg + godBoost + scopeBoost;",
    "    }",
    "",
    "    // Collect candidate edges that connect kept nodes",
    "    let keptEdges = (Array.isArray(allEdgesArr) ? allEdgesArr.slice() : []).filter(e => keptNodeIds.has(e.source) && keptNodeIds.has(e.target));",
    "    if (keptEdges.length > edgesBudget) {",
    "      keptEdges.sort((a, b) => edgeScore(b) - edgeScore(a));",
    "      keptEdges = keptEdges.slice(0, edgesBudget);",
    "    }",
    "",
    "    return { nodes: keptNodes, edges: keptEdges };",
    "  }",
    "",
    "  // Use consolidation to produce the simulated subset (this keeps layout responsive)",
    "  const combined = consolidateNodesAndEdges(Array.from(nodeMapAll.values()), Array.isArray(edges) ? edges : [], godIds);",
    "  const candidateNodes = combined.nodes.slice(0, 600); // safety cap for layout",
    "",
    "  // Cluster by project when multiple projectRoots are present (useful",
    "  // for the 'global' memory-scope view where nodes come from many projects).",
    "  const projectBuckets = new Map();",
    "  for (const n of candidateNodes) {",
    "    try {",
    "      const root = (n.metadata && (n.metadata.projectRoot || n.metadata.project_root)) || \"__no_project__\";",
    "      const arr = projectBuckets.get(root) || [];",
    "      arr.push(n);",
    "      projectBuckets.set(root, arr);",
    "    } catch {",
    "      const arr = projectBuckets.get(\"__no_project__\") || [];",
    "      arr.push(n);",
    "      projectBuckets.set(\"__no_project__\", arr);",
    "    }",
    "  }",
    "",
    "  let sim = [];",
    "  const roots = Array.from(projectBuckets.keys()).sort((a, b) => a.localeCompare(b));",
    "  const tierOrder = [\"project\", \"god\", \"child\", \"edge\"];",
    "  const shellScale = Math.min(W, H) * layoutScale;",
    "  const clusterRingRadius = roots.length > 1",
    "    ? shellScale * Math.min(0.38, Math.max(0.24, 0.14 + roots.length * 0.04))",
    "    : 0;",
    "  const tierRadiusByName = {",
    "    project: Math.max(34, shellScale * 0.05),",
    "    god: Math.max(84, shellScale * 0.12),",
    "    child: Math.max(132, shellScale * 0.19),",
    "    edge: Math.max(180, shellScale * 0.27),",
    "  };",
    "",
    "  function getScope(n) {",
    "    try {",
    "      return (n.metadata && (n.metadata.memoryScope || n.metadata.memory_scope)) || \"project\";",
    "    } catch {",
    "      return \"project\";",
    "    }",
    "  }",
    "",
    "  function classifyTier(n, degree, isGod) {",
    "    const kind = n.kind || \"default\";",
    "    const scope = getScope(n);",
    "    if (kind === \"file\" || kind === \"module\") return \"project\";",
    "    if (scope === \"project\" && degree >= 6 && (kind === \"class\" || kind === \"interface\" || kind === \"type\" || kind === \"function\" || kind === \"method\")) {",
    "      return \"project\";",
    "    }",
    "    if (isGod || degree >= 5) return \"god\";",
    "    if (degree >= 2) return \"child\";",
    "    return \"edge\";",
    "  }",
    "",
    "  function nodeImportance(n, degree, tier, isGod) {",
    "    const kind = n.kind || \"default\";",
    "    const scope = getScope(n);",
    "    let score = degree * 10;",
    "    if (PROJECT_NODE_KINDS.has(kind)) score += 120;",
    "    if (scope === \"project\") score += 20;",
    "    if (scope === \"global\") score += 12;",
    "    if (scope === \"entity\") score += 8;",
    "    if (tier === \"project\") score += 90;",
    "    else if (tier === \"god\") score += 60;",
    "    else if (tier === \"child\") score += 20;",
    "    if (isGod) score += 150;",
    "    return score;",
    "  }",
    "",
    "  function placeCluster(root, cx, cy, nodesInCluster) {",
    "    const tierBuckets = { project: [], god: [], child: [], edge: [] };",
    "    const clusterSize = Math.max(1, nodesInCluster.length);",
    "    const projectFill = projectFillColor(root);",
    "    for (const n of nodesInCluster) {",
    "      const degree = degreeMap.get(n.id) || 0;",
    "      const isGod = godIds.has(n.id);",
    "      const tier = classifyTier(n, degree, isGod);",
    "      tierBuckets[tier].push({ node: n, degree, tier, isGod });",
    "    }",
    "    for (const tier of tierOrder) {",
    "      tierBuckets[tier].sort((a, b) => { const diff = nodeImportance(b.node, b.degree, b.tier, b.isGod) - nodeImportance(a.node, a.degree, a.tier, a.isGod); return diff !== 0 ? diff : a.node.id.localeCompare(b.node.id); });",
    "    }",
    "",
    "    const tierSpacing = { project: 42 * layoutScale, god: 36 * layoutScale, child: 30 * layoutScale, edge: 24 * layoutScale };",
    "    const tierRadii = {",
    "      project: tierRadiusByName.project,",
    "      god: tierRadiusByName.god,",
    "      child: tierRadiusByName.child,",
    "      edge: tierRadiusByName.edge,",
    "    };",
    "",
    "    for (const tier of tierOrder) {",
    "      const bucket = tierBuckets[tier];",
    "      if (bucket.length === 0) continue;",
    "      const requiredCircumference = bucket.reduce((sum, item) => sum + nodeCollisionRadius(item.node) * 2 + tierSpacing[tier], 0);",
    "      const packedRadius = bucket.length > 1 ? requiredCircumference / (Math.PI * 2) : 0;",
    "      const densityBoost = Math.min(24, Math.sqrt(bucket.length) * (tier === 'project' ? 3.6 : tier === 'god' ? 3.0 : tier === 'child' ? 2.6 : 2.2));",
    "      const baseRadius = tier === 'project' && bucket.length === 1 ? 0 : Math.max(tierRadii[tier], packedRadius, densityBoost);",
    "      const angleOffset = stableAngle(root, tier);",
    "      const angleStep = bucket.length > 0 ? (Math.PI * 2) / bucket.length : 0;",
    "      for (let i = 0; i < bucket.length; i++) {",
    "        const item = bucket[i];",
    "        const n = item.node;",
    "        const angleJitter = (seededNoise(root + '::a::' + n.id + '::' + tier) - 0.5) * angleStep * 0.22;",
    "        const radiusJitter = baseRadius === 0 ? 0 : (seededNoise(root + '::r::' + n.id + '::' + tier) - 0.5) * Math.min(14, Math.max(4, baseRadius * 0.12));",
    "        const angle = angleOffset + angleStep * i + angleJitter;",
    "        const localRadius = baseRadius + radiusJitter;",
    "        const x = cx + Math.cos(angle) * localRadius;",
    "        const y = cy + Math.sin(angle) * localRadius;",
    "        const clampedX = Math.max(20, Math.min(W - 20, x));",
    "        const clampedY = Math.max(20, Math.min(H - 20, y));",
    "        const prior = priorPositions.get(n.id);",
    "        const startX = prior && Number.isFinite(prior.x) ? prior.x : clampedX;",
    "        const startY = prior && Number.isFinite(prior.y) ? prior.y : clampedY;",
    "        sim.push({",
    "          id: n.id,",
    "          label: n.label || n.id,",
    "          kind: n.kind || 'default',",
    "          sourceFile: n.sourceFile || '',",
    "          sourceLocation: n.sourceLocation ?? null,",
    "          confidence: n.confidence || 'EXTRACTED',",
    "          confidenceScore: Number.isFinite(Number(n.confidenceScore)) ? Number(n.confidenceScore) : 1,",
    "          lastVerified: Number.isFinite(Number(n.lastVerified)) ? Number(n.lastVerified) : 0,",
    "          queryCount: Number.isFinite(Number(n.queryCount)) ? Number(n.queryCount) : 0,",
    "          metadata: n.metadata || {},",
    "          validUntil: n.validUntil,",
    "          invalidatedByCommit: n.invalidatedByCommit,",
    "          memoryScope: getScope(n),",
    "          tier,",
    "          clusterRoot: root,",
    "          clusterX: cx,",
    "          clusterY: cy,",
    "          tierRadius: baseRadius,",
    "          projectFill,",
    "          outlineColor: scopeOutlineColor(getScope(n)),",
    "          shape: tierShape(tier),",
    "          halo: tier === 'project' ? 12 : tier === 'god' ? 9 : tier === 'child' ? 6 : 4,",
    "          isGod: item.isGod,",
    "          seenBefore: !!prior,",
    "          homeX: clampedX,",
    "          homeY: clampedY,",
    "          x: startX,",
    "          y: startY,",
    "          vx: 0, vy: 0,",
    "        });",
    "      }",
    "    }",
    "  }",
    "",
    "  if (roots.length > 1) {",
    "    for (let i = 0; i < roots.length; i++) {",
    "      const root = roots[i];",
    "      const nodesInCluster = projectBuckets.get(root) || [];",
    "      const clusterAngle = (i / roots.length) * Math.PI * 2;",
    "      const cx = W / 2 + Math.cos(clusterAngle) * clusterRingRadius;",
    "      const cy = H / 2 + Math.sin(clusterAngle) * clusterRingRadius;",
    "      placeCluster(root, cx, cy, nodesInCluster);",
    "    }",
    "  } else {",
    "    const root = roots[0] || \"__no_project__\";",
    "    const nodesInCluster = projectBuckets.get(root) || [];",
    "    placeCluster(root, W / 2, H / 2, nodesInCluster);",
    "  }",
    "",
    "  if (sim.length === 0) {",
    "    ctx.fillStyle = \"#71717a\";",
    "    ctx.font = \"13px SF Mono, Monaco, monospace\";",
    "    ctx.textAlign = \"center\";",
    "    ctx.fillText(\"No graph data yet\", W / 2, H / 2);",
    "    return;",
    "  }",
    "",
    "  // Build a quick id->node map for edge wiring",
    "  const nodeById = new Map(sim.map((n) => [n.id, n]));",
    "  const springs = [];",
    "  if (Array.isArray(edges)) {",
    "    for (const e of edges) {",
    "      const a = nodeById.get(e.source);",
    "      const b = nodeById.get(e.target);",
    "      if (a && b) springs.push({ a, b, relation: e.relation });",
    "    }",
    "  }",
    "",
    "  const nodeConnectionStats = new Map();",
    "  const getNodeConnectionStats = (id) => {",
    "    const existing = nodeConnectionStats.get(id);",
    "    if (existing) return existing;",
    "    const created = { incoming: 0, outgoing: 0, links: 0, neighbors: new Set() };",
    "    nodeConnectionStats.set(id, created);",
    "    return created;",
    "  };",
    "  for (const s of springs) {",
    "    const outStats = getNodeConnectionStats(s.a.id);",
    "    outStats.outgoing++;",
    "    outStats.links++;",
    "    outStats.neighbors.add(s.b.id);",
    "    const inStats = getNodeConnectionStats(s.b.id);",
    "    inStats.incoming++;",
    "    inStats.links++;",
    "    inStats.neighbors.add(s.a.id);",
    "  }",
    "",
    "  // Expose visible nodes/edges so other UI pieces (legend) can summarize",
    "  try {",
    "    window.__engram_graph_visibleNodes = sim.map(n => n.id);",
    "    window.__engram_graph_visibleEdges = springs.map(s => ({ source: s.a.id, target: s.b.id, relation: s.relation }));",
    "    window.__engram_graph_visibleTiers = sim.reduce((acc, n) => {",
    "      acc[n.tier] = (acc[n.tier] || 0) + 1;",
    "      return acc;",
    "    }, { project: 0, god: 0, child: 0, edge: 0 });",
    "  } catch (e) {}",
    "",
    "  function nodeRadiusFor(n) {",
    "    return visualNodeRadius(n.tier, degreeMap.get(n.id) || 0);",
    "  }",
    "",
    "  function nodeCollisionRadius(n) {",
    "    const degree = degreeMap.get(n.id) || 0;",
    "    const base = nodeRadiusFor(n);",
    "    const shellPad = n.tier === 'project' ? 8 : n.tier === 'god' ? 6 : n.tier === 'child' ? 5 : 4;",
    "    const degreePad = Math.min(4.5, degree * 0.2);",
    "    const haloPad = (n.halo || 0) * 0.2;",
    "    return (base + shellPad + degreePad + haloPad) * layoutScale;",
    "  }",
    "",
    "  function nodeStability(n) {",
    "    const degree = degreeMap.get(n.id) || 0;",
    "    let stability = 1.0;",
    "    if (n.tier === 'project') stability += 4.0;",
    "    else if (n.tier === 'god') stability += 2.8;",
    "    else if (n.tier === 'child') stability += 1.5;",
    "    else stability += 0.8;",
    "    if (n.isGod) stability += 1.8;",
    "    if (n.seenBefore) stability += layoutMode === 'stream' ? 4.0 : 2.2;",
    "    stability += Math.min(3, degree * 0.18);",
    "    return stability;",
    "  }",
    "",
    "  function edgeTargetLength(a, b, relation) {",
    "    const degreeA = degreeMap.get(a.id) || 0;",
    "    const degreeB = degreeMap.get(b.id) || 0;",
    "    const base = Math.max(SPRING_LENGTH, nodeCollisionRadius(a) + nodeCollisionRadius(b) + COLLISION_GAP);",
    "    const relationBias = relation === 'contains' ? -10 : relation === 'imports' ? 6 : relation === 'depends_on' ? 10 : relation === 'rationale_for' ? 12 : relation === 'similar_to' ? 4 : 0;",
    "    const degreeBias = Math.min(24, (degreeA + degreeB) * 0.6);",
    "    return base + relationBias + degreeBias;",
    "  }",
    "",
    "  const maxCollisionRadius = sim.reduce((max, n) => Math.max(max, nodeCollisionRadius(n)), 0);",
    "",
    "  const tooltipEl = (() => {",
    "    let el = document.getElementById(\"graph-tooltip\");",
    "    if (!el && typeof document.createElement === 'function' && document.body) {",
    "      el = document.createElement(\"div\");",
    "      el.id = \"graph-tooltip\";",
    "      document.body.appendChild(el);",
    "    }",
    "    return el;",
    "  })();",
    "  const formatDateTime = (value) => {",
    "    const ms = Number(value);",
    "    if (!Number.isFinite(ms) || ms <= 0) return \"—\";",
    "    try { return new Date(ms).toLocaleString(); } catch { return String(ms); }",
    "  };",
    "  const screenPointForNode = (node) => ({ x: viewX + node.x * zoom, y: viewY + node.y * zoom });",
    "  const clampTooltipPoint = (x, y, w, h) => {",
    "    const margin = 12;",
    "    const maxX = Math.max(margin, (window.innerWidth || W) - w - margin);",
    "    const maxY = Math.max(margin, (window.innerHeight || H) - h - margin);",
    "    return { x: Math.max(margin, Math.min(maxX, x)), y: Math.max(margin, Math.min(maxY, y)) };",
    "  };",
    "  const buildNodeTooltipHtml = (node) => {",
    "    const meta = node.metadata || {};",
    "    const stats = getNodeConnectionStats(node.id);",
    "    const neighbors = Array.from(stats.neighbors || []).slice(0, 4).map((id) => {",
    "      const found = nodeById.get(id);",
    "      return found ? found.label : id;",
    "    }).join(', ');",
    "    const scope = node.memoryScope || meta.memoryScope || meta.memory_scope || 'project';",
    "    const projectRoot = meta.projectRoot || meta.project_root || '—';",
    "    const projectBranch = meta.projectBranch || meta.project_branch || '—';",
    "    const fileBirth = meta.fileBirthtimeMs || meta.file_birthtime_ms || null;",
    "    const fileMtime = meta.fileMtimeMs || meta.file_mtime_ms || null;",
    "    const rows = [",
    "      ['ID', node.id],",
    "      ['Kind', node.kind || 'default'],",
    "      ['Memory', scope],",
    "      ['Project', projectRoot],",
    "      ['Branch', projectBranch],",
    "      ['Created', formatDateTime(fileBirth)],",
    "      ['Modified', formatDateTime(fileMtime || node.lastVerified)],",
    "      ['Verified', formatDateTime(node.lastVerified)],",
    "      ['Links', String(stats.links || 0)],",
    "      ['In / Out', (stats.incoming || 0) + ' / ' + (stats.outgoing || 0)],",
    "      ['Neighbors', neighbors || '—'],",
    "      ['Confidence', (node.confidence || 'EXTRACTED') + ' · ' + Number(node.confidenceScore || 0).toFixed(2)],",
    "      ['Queries', String(node.queryCount || 0)],",
    "    ];",
    "    if (node.validUntil) rows.push(['Valid until', formatDateTime(node.validUntil)]);",
    "    if (node.invalidatedByCommit) rows.push(['Invalidated by', node.invalidatedByCommit]);",
    "    return '<div class=\"tooltip-title\">' + escHtml(node.label || node.id) + '</div>' + rows.map(([label, value]) => '<div class=\"tooltip-row\"><div class=\"tooltip-label\">' + escHtml(label) + '</div><div class=\"tooltip-value\">' + escHtml(value) + '</div></div>').join('');",
    "  };",
    "  const showTooltip = (node, clientX, clientY) => {",
    "    if (!tooltipEl || !node) return;",
    "    const currentNodeId = tooltipEl.getAttribute('data-node-id');",
    "    if (currentNodeId !== node.id) {",
    "      tooltipEl.innerHTML = buildNodeTooltipHtml(node);",
    "      tooltipEl.setAttribute('data-node-id', node.id);",
    "    }",
    "    tooltipEl.style.display = 'block';",
    "    tooltipEl.classList.add('show');",
    "    const anchor = typeof clientX === 'number' && typeof clientY === 'number' ? { x: clientX, y: clientY } : screenPointForNode(node);",
    "    const rect = tooltipEl.getBoundingClientRect();",
    "    const point = clampTooltipPoint(anchor.x + 14, anchor.y + 14, rect.width || 280, rect.height || 180);",
    "    tooltipEl.style.left = point.x + 'px';",
    "    tooltipEl.style.top = point.y + 'px';",
    "  };",
    "  const hideTooltip = () => {",
    "    if (!tooltipEl) return;",
    "    tooltipEl.classList.remove('show');",
    "    tooltipEl.style.display = 'none';",
    "    tooltipEl.removeAttribute('data-node-id');",
    "  };",
    "  const pickNodeAt = (worldX, worldY) => {",
    "    let hit = null;",
    "    let best = Infinity;",
    "    for (const n of sim) {",
    "      const dx = n.x - worldX;",
    "      const dy = n.y - worldY;",
    "      const hitRadius = Math.max(nodeRadiusFor(n) + 8, nodeCollisionRadius(n) * 0.72);",
    "      const dist2 = dx * dx + dy * dy;",
    "      if (dist2 <= hitRadius * hitRadius && dist2 < best) {",
    "        best = dist2;",
    "        hit = n;",
    "      }",
    "    }",
    "    return hit;",
    "  };",
    "",
    "  function computeLayoutMetrics() {",
    "    let overlapCount = 0;",
    "    let pairCount = 0;",
    "    let meanEdgeStretch = 0;",
    "    let maxEdgeStretch = 0;",
    "    let meanShellError = 0;",
    "    const N = sim.length;",
    "    const countPair = (a, b) => {",
    "      const dx = b.x - a.x;",
    "      const dy = b.y - a.y;",
    "      const dist2 = dx * dx + dy * dy + 0.01;",
    "      const dist = Math.sqrt(dist2);",
    "      const minDist = nodeCollisionRadius(a) + nodeCollisionRadius(b) + COLLISION_GAP;",
    "      pairCount++;",
    "      if (dist < minDist) overlapCount++;",
    "    };",
    "    if (N > 400) {",
    "      const cellSize = Math.max(32, SPRING_LENGTH * 1.25);",
    "      const buckets = new Map();",
    "      const nodeIndex = new Map();",
    "      for (let i = 0; i < N; i++) {",
    "        const n = sim[i];",
    "        nodeIndex.set(n.id, i);",
    "        const cx = Math.floor(n.x / cellSize);",
    "        const cy = Math.floor(n.y / cellSize);",
    "        const key = cx + \",\" + cy;",
    "        const arr = buckets.get(key) || [];",
    "        arr.push(n);",
    "        buckets.set(key, arr);",
    "      }",
    "      for (let i = 0; i < N; i++) {",
    "        const a = sim[i];",
    "        const acx = Math.floor(a.x / cellSize);",
    "        const acy = Math.floor(a.y / cellSize);",
    "        for (let dx = -1; dx <= 1; dx++) {",
    "          for (let dy = -1; dy <= 1; dy++) {",
    "            const key = (acx + dx) + \",\" + (acy + dy);",
    "            const arr = buckets.get(key);",
    "            if (!arr) continue;",
    "            for (const b of arr) {",
    "              const j = nodeIndex.get(b.id);",
    "              if (j <= i) continue;",
    "              countPair(a, b);",
    "            }",
    "          }",
    "        }",
    "      }",
    "    } else {",
    "      for (let i = 0; i < sim.length; i++) {",
    "        const a = sim[i];",
    "        for (let j = i + 1; j < sim.length; j++) {",
    "          countPair(a, sim[j]);",
    "        }",
    "      }",
    "    }",
    "    for (const s of springs) {",
    "      const a = s.a;",
    "      const b = s.b;",
    "      const dx = b.x - a.x;",
    "      const dy = b.y - a.y;",
    "      const dist = Math.sqrt(dx * dx + dy * dy) || 1;",
    "      const target = edgeTargetLength(a, b, s.relation);",
    "      const stretch = Math.abs(dist - target) / Math.max(1, target);",
    "      meanEdgeStretch += stretch;",
    "      if (stretch > maxEdgeStretch) maxEdgeStretch = stretch;",
    "    }",
    "    for (const n of sim) {",
    "      const cx = n.clusterX ?? W / 2;",
    "      const cy = n.clusterY ?? H / 2;",
    "      const dx = n.x - cx;",
    "      const dy = n.y - cy;",
    "      const dist = Math.sqrt(dx * dx + dy * dy) || 1;",
    "      const target = n.tierRadius || (NODE_SHELLS[n.tier] || NODE_SHELLS.edge).radius;",
    "      meanShellError += Math.abs(dist - target) / Math.max(1, target);",
    "    }",
    "    return {",
    "      overlapCount,",
    "      overlapRatio: pairCount > 0 ? overlapCount / pairCount : 0,",
    "      meanEdgeStretch: springs.length > 0 ? meanEdgeStretch / springs.length : 0,",
    "      maxEdgeStretch,",
    "      meanShellError: sim.length > 0 ? meanShellError / sim.length : 0,",
    "      nodeCount: N,",
    "      edgeCount: springs.length,",
    "    };",
    "  }",
    "",
    "  // Viewport transform (pan + zoom)",

    "  let viewX = Number.isFinite(Number(persistedView.viewX)) ? Number(persistedView.viewX) : 0;",
    "  let viewY = Number.isFinite(Number(persistedView.viewY)) ? Number(persistedView.viewY) : 0;",
    "  let zoom = Number.isFinite(Number(persistedView.zoom)) ? Number(persistedView.zoom) : 1;",
    "  const syncViewState = () => {",
    "    window.__engram_graph_viewState = { viewX, viewY, zoom };",
    "  };",
    "  let draggingView = false, dragStartX = 0, dragStartY = 0;",
    "  let selectedId = null;",
    "  let selectedEdge = null;",
    "  let hoveredId = null;",
    "  let lastMouseX = null, lastMouseY = null;",
    "",
    "  // \u2500\u2500\u2500 Physics step (tuned to settle faster and avoid long oscillations) \u2500\u2500\u2500",
    "  // REPULSION scales down for large graphs (so springs can pull clusters together)",
    "  const REPULSION = Math.max(90, Math.floor(1100 * Math.min(1, 320 / Math.max(1, sim.length))));",
    "  // Stronger spring constant to favor edge clustering over global repulsion",
    "  const SPRING_K = 0.08;",
    "  // Spring length tuned by viewport size (keeps connected nodes reasonably close)",
    "  const SPRING_LENGTH = Math.max(54, Math.min(120, Math.floor(Math.sqrt(W * H) / 7))) * layoutScale;",
    "  const DAMPING = 0.76;",
    "  const GLOBAL_GRAVITY = 0.00035;",
    "  const CLUSTER_GRAVITY = 0.001;",
    "  const COLLISION_GAP = 16 * layoutScale;",
    "  const COLLISION_FORCE = 0.22;",
    "  const MAX_SPEED = 8.2;",

    "",
    "  function step() {",
    "    // Position-based layout solver: nodes move directly toward their home slots",
    "    // and then resolve springs + collisions without storing momentum.",
    "    let maxMove = 0;",
    "    const startPositions = sim.map((n) => ({ x: n.x, y: n.y }));",
    "    const N = sim.length;",
    "",
    "    const clampNode = (n) => {",
    "      const cx = typeof n.clusterX === 'number' ? n.clusterX : W / 2;",
    "      const cy = typeof n.clusterY === 'number' ? n.clusterY : H / 2;",
    "      const dx = n.x - cx;",
    "      const dy = n.y - cy;",
    "      const dist = Math.sqrt(dx * dx + dy * dy) || 1;",
    "      const shell = NODE_SHELLS[n.tier] || NODE_SHELLS.edge;",
    "      const tierLimit = n.tier === 'project' ? 1.22 : n.tier === 'god' ? 1.38 : n.tier === 'child' ? 1.54 : 1.72;",
    "      const maxRadius = (n.tierRadius || shell.radius) + nodeCollisionRadius(n) * tierLimit + (layoutMode === 'stream' ? 14 : 8);",
    "      if (dist > maxRadius) {",
    "        const ratio = maxRadius / dist;",
    "        n.x = cx + dx * ratio;",
    "        n.y = cy + dy * ratio;",
    "      }",
    "    };",
    "",
    "    const resolveCollisionsPass = (strength = 1) => {",
    "      let overlapCount = 0;",
    "      const collisionCellSize = Math.max(48, maxCollisionRadius * 2 + COLLISION_GAP * 2);",
    "      const buckets = new Map();",
    "      const nodeIndex = new Map();",
    "      for (let i = 0; i < N; i++) {",
    "        const n = sim[i];",
    "        nodeIndex.set(n.id, i);",
    "        const cx = Math.floor(n.x / collisionCellSize);",
    "        const cy = Math.floor(n.y / collisionCellSize);",
    "        const key = cx + ',' + cy;",
    "        const arr = buckets.get(key) || [];",
    "        arr.push(n);",
    "        buckets.set(key, arr);",
    "      }",
    "      for (let i = 0; i < N; i++) {",
    "        const a = sim[i];",
    "        const acx = Math.floor(a.x / collisionCellSize);",
    "        const acy = Math.floor(a.y / collisionCellSize);",
    "        for (let dx = -1; dx <= 1; dx++) {",
    "          for (let dy = -1; dy <= 1; dy++) {",
    "            const key = (acx + dx) + ',' + (acy + dy);",
    "            const arr = buckets.get(key);",
    "            if (!arr) continue;",
    "            for (const b of arr) {",
    "              const j = nodeIndex.get(b.id);",
    "              if (j <= i) continue;",
    "              const dx_ = b.x - a.x;",
    "              const dy_ = b.y - a.y;",
    "              const minDist = nodeCollisionRadius(a) + nodeCollisionRadius(b) + COLLISION_GAP;",
    "              const dist2 = dx_ * dx_ + dy_ * dy_ + 0.0001;",
    "              const dist = Math.sqrt(dist2);",
    "              if (dist >= minDist) continue;",
    "              overlapCount++;",
    "              const angle = dist > 0.0001 ? Math.atan2(dy_, dx_) : stableAngle(a.id, b.id);",
    "              const ux = Math.cos(angle);",
    "              const uy = Math.sin(angle);",
    "              const overlap = (minDist - dist) * 0.5 * strength;",
    "              const sa = nodeStability(a);",
    "              const sb = nodeStability(b);",
    "              const total = sa + sb;",
    "              const aShift = overlap * (sb / total);",
    "              const bShift = overlap * (sa / total);",
    "              a.x -= ux * aShift;",
    "              a.y -= uy * aShift;",
    "              b.x += ux * bShift;",
    "              b.y += uy * bShift;",
    "            }",
    "          }",
    "        }",
    "      }",
    "      return overlapCount;",
    "    };",
    "",
    "    const streamPressure = Math.max(perfState.avgTotalMs || 0, perfState.avgLayoutMs || 0);",
    "    const relaxPasses = layoutMode === 'stream' ? (streamPressure > 28 ? 1 : N > 400 ? 1 : 2) : (N > 400 ? 4 : 5);",
    "    for (let pass = 0; pass < relaxPasses; pass++) {",
    "      for (const n of sim) {",
    "        const homeX = typeof n.homeX === 'number' ? n.homeX : (n.clusterX ?? W / 2);",
    "        const homeY = typeof n.homeY === 'number' ? n.homeY : (n.clusterY ?? H / 2);",
    "        const homePull = n.tier === 'project' ? 0.26 : n.tier === 'god' ? 0.2 : n.tier === 'child' ? 0.16 : 0.12;",
    "        n.x += (homeX - n.x) * homePull;",
    "        n.y += (homeY - n.y) * homePull;",
    "      }",
    "",
    "      for (const s of springs) {",
    "        const a = s.a;",
    "        const b = s.b;",
    "        const dx = b.x - a.x;",
    "        const dy = b.y - a.y;",
    "        const dist = Math.sqrt(dx * dx + dy * dy) || 1;",
    "        const target = edgeTargetLength(a, b, s.relation);",
    "        const diff = dist - target;",
    "        const sa = nodeStability(a);",
    "        const sb = nodeStability(b);",
    "        const total = sa + sb;",
    "        const relationPull = s.relation === 'contains' ? 0.12 : s.relation === 'depends_on' ? 0.1 : s.relation === 'imports' ? 0.09 : s.relation === 'similar_to' ? 0.07 : 0.08;",
    "        const ux = dx / dist;",
    "        const uy = dy / dist;",
    "        const shift = diff * relationPull;",
    "        a.x += ux * shift * (sb / total);",
    "        a.y += uy * shift * (sb / total);",
    "        b.x -= ux * shift * (sa / total);",
    "        b.y -= uy * shift * (sa / total);",
    "      }",
    "",
    "      const overlapCount = resolveCollisionsPass(pass === 0 ? 1 : 0.9);",
    "      for (const n of sim) clampNode(n);",
    "      if (overlapCount === 0 && pass > 1) break;",
    "    }",
    "",
    "    const finalOverlapPasses = layoutMode === 'stream' ? (streamPressure > 28 ? 2 : 4) : 24;",
    "    let finalOverlap = 0;",
    "    for (let pass = 0; pass < finalOverlapPasses; pass++) {",
    "      finalOverlap = resolveCollisionsPass(layoutMode === 'stream' ? 1.4 + pass * 0.06 : 2.0 + pass * 0.12);",
    "      for (const n of sim) clampNode(n);",
    "      if (finalOverlap === 0) break;",
    "    }",
    "",
    "    maxMove = 0;",
    "    for (let i = 0; i < sim.length; i++) {",
    "      const n = sim[i];",
    "      const start = startPositions[i];",
    "      const dx = n.x - start.x;",
    "      const dy = n.y - start.y;",
    "      const move = Math.sqrt(dx * dx + dy * dy);",
    "      if (move > maxMove) maxMove = move;",
    "    }",
    "    return maxMove;",
    "  }",
    "",
    "  // Pre-relaxation: run a short synchronous settle pass to reduce visible bouncing.",
    "  // Stop early when position changes have settled to a low threshold. Cap iterations",
    "  // to avoid excessive blocking on huge graphs. For very dense graphs we use",
    "  // more iterations to let springs pull clusters together.",
    "  const layoutStart = perfNow();",
    "  let layoutMetrics = null;",
    "  if (layoutMode === \"stream\") {",
    "    try {",
    "      const quickIters = Math.max(1, streamPressure > 28 ? 1 : Math.min(3, Math.ceil(sim.length / 30)));",
    "      for (let i = 0; i < quickIters; i++) step();",
    "      layoutMetrics = computeLayoutMetrics();",
    "      window.__engram_graph_layoutMetrics = layoutMetrics;",
    "      window.__engram_graph_layoutNodes = sim.map((n) => ({",
    "        id: n.id,",
    "        x: n.x,",
    "        y: n.y,",
    "        tier: n.tier,",
    "        clusterRoot: n.clusterRoot,",
    "        projectFill: n.projectFill,",
    "        outlineColor: n.outlineColor,",
    "        shape: n.shape,",
    "        halo: n.halo,",
    "      }));",
    "      window.__engram_graph_layoutSprings = springs.map((s) => ({ source: s.a.id, target: s.b.id, relation: s.relation }));",
    "      layoutDuration = perfNow() - layoutStart;",
    "    } catch (e) {",
    "      // If the browser is very constrained, stream mode falls back to the current pass only",
    "    }",
    "    draw();",
    "    const totalMs = perfNow() - totalStart;",
    "    perfState.sampleCount = (perfState.sampleCount || 0) + 1;",
    "    const alpha = perfState.sampleCount < 5 ? 0.5 : 0.18;",
    "    perfState.avgTotalMs = perfState.avgTotalMs ? perfState.avgTotalMs * (1 - alpha) + totalMs * alpha : totalMs;",
    "    perfState.avgLayoutMs = perfState.avgLayoutMs ? perfState.avgLayoutMs * (1 - alpha) + layoutDuration * alpha : layoutDuration;",
    "    perfState.maxTotalMs = Math.max(perfState.maxTotalMs || 0, totalMs);",
    "    perfState.maxLayoutMs = Math.max(perfState.maxLayoutMs || 0, layoutDuration);",
    "    perfState.lastNodeCount = sim.length;",
    "    perfState.lastEdgeCount = springs.length;",
    "    if (layoutDuration > 24 || totalMs > 32) perfState.slowFrames = (perfState.slowFrames || 0) + 1;",
    "    window.__engram_graph_perfMetrics = perfState;",
    "    return;",
    "  }",
    "  try {",
    "    const base = Math.floor(80000 / Math.max(1, sim.length));",
    "    const maxIters = Math.min(2000, Math.max(120, base));",
    "    for (let i = 0; i < maxIters; i++) {",
    "      const maxSpeed = step();",
    "      if (maxSpeed < 0.02 && i > 20) break;",
    "    }",
    "    layoutMetrics = computeLayoutMetrics();",
    "    layoutDuration = perfNow() - layoutStart;",
    "    const extraIters = layoutMetrics.meanShellError > 0.18",
    "      ? Math.min(180, Math.max(24, Math.round(layoutMetrics.meanShellError * 120)))",
    "      : 0;",
    "    for (let i = 0; i < extraIters; i++) {",
    "      const maxSpeed = step();",
    "      if (maxSpeed < 0.015 && i > 20) break;",
    "    }",
    "    layoutMetrics = computeLayoutMetrics();",
    "  } catch (e) {",
    "    // If the browser is very constrained, skip pre-relax and continue",
    "  }",
    "  try {",
    "    window.__engram_graph_layoutMetrics = layoutMetrics;",
    "    window.__engram_graph_layoutNodes = sim.map((n) => ({",
    "      id: n.id,",
    "      x: n.x,",
    "      y: n.y,",
    "      tier: n.tier,",
    "      clusterRoot: n.clusterRoot,",
    "      projectFill: n.projectFill,",
    "      outlineColor: n.outlineColor,",
    "      shape: n.shape,",
    "      halo: n.halo,",
    "    }));",
    "    window.__engram_graph_layoutSprings = springs.map((s) => ({ source: s.a.id, target: s.b.id, relation: s.relation }));",
    "  } catch (e) {}",
    "",
    "  function autoFitBounds(nodesToFit) {",
    "    if (!autoFitView || !Array.isArray(nodesToFit) || nodesToFit.length === 0) return;",
    "    let minX = Infinity;",
    "    let minY = Infinity;",
    "    let maxX = -Infinity;",
    "    let maxY = -Infinity;",
    "    for (const n of nodesToFit) {",
    "      const radius = nodeRadiusFor(n) + 10;",
    "      minX = Math.min(minX, n.x - radius);",
    "      minY = Math.min(minY, n.y - radius);",
    "      maxX = Math.max(maxX, n.x + radius);",
    "      maxY = Math.max(maxY, n.y + radius);",
    "    }",
    "    const spanX = Math.max(1, maxX - minX);",
    "    const spanY = Math.max(1, maxY - minY);",
    "    const padding = Math.max(96, Math.min(W, H) * (layoutMode === 'stream' ? 0.22 : 0.18));",
    "    const targetZoom = Math.max(0.18, Math.min(3, Math.min((W - padding * 2) / spanX, (H - padding * 2) / spanY) * 0.95));",
    "    const centerX = (minX + maxX) / 2;",
    "    const centerY = (minY + maxY) / 2;",
    "    const ease = layoutMode === 'stream' ? 0.4 : 0.2;",
    "    viewX += (((W / 2) - centerX * targetZoom) - viewX) * ease;",
    "    viewY += (((H / 2) - centerY * targetZoom) - viewY) * ease;",
    "    zoom += (targetZoom - zoom) * ease;",
    "  }",
    "",
    "  autoFitBounds(sim);",
    "",
    "  // \u2500\u2500\u2500 Render \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
    "  function draw() {",
    "    ctx.clearRect(0, 0, W, H);",
    "    ctx.save();",
    "    ctx.translate(viewX, viewY);",
    "    ctx.scale(zoom, zoom);",
    "",
    "    const clusterMap = new Map();",
    "    for (const n of sim) {",
    "      if (!clusterMap.has(n.clusterRoot)) {",
    "        clusterMap.set(n.clusterRoot, {",
    "          x: n.clusterX ?? W / 2,",
    "          y: n.clusterY ?? H / 2,",
    "          fill: n.projectFill || projectFillColor(n.clusterRoot || n.id),",
    "        });",
    "      }",
    "    }",
    "    ctx.save();",
    "    for (const cluster of clusterMap.values()) {",
    "      const rings = [",
    "        { radius: Math.max(18, tierRadiusByName.project * 1.08), alpha: 0.08 },",
    "        { radius: Math.max(56, tierRadiusByName.god * 1.02), alpha: 0.05 },",
    "        { radius: Math.max(96, tierRadiusByName.child * 0.98), alpha: 0.03 },",
    "      ];",
    "      for (const ring of rings) {",
    "        ctx.beginPath();",
    "        ctx.arc(cluster.x, cluster.y, ring.radius, 0, Math.PI * 2);",
    "        ctx.strokeStyle = cluster.fill;",
    "        ctx.globalAlpha = ring.alpha;",
    "        ctx.lineWidth = 1.25 / Math.max(zoom, 0.6);",
    "        ctx.stroke();",
    "      }",
    "    }",
    "    ctx.restore();",
    "",
    "",
    "    // Draw edges (lines) first",
    "    const RELATION_STYLES = {",
    "      contains: { color: '#9CA3AF', width: 1, dash: [] },",
    "      imports: { color: '#60A5FA', width: 1, dash: [6,4] },",
    "      similar_to: { color: '#FBBF24', width: 1, dash: [2,4] },",
    "      depends_on: { color: '#10B981', width: 1.25, dash: [] },",
    "      triggered_by: { color: '#A78BFA', width: 1, dash: [4,3] },",
    "      rationale_for: { color: '#EF4444', width: 1, dash: [2,2] },",
    "      default: { color: '#6B7280', width: 0.9, dash: [] },",
    "    };",
    "",
    "    for (const s of springs) {",
    "      const a = s.a;",
    "      const b = s.b;",
    "      const style = RELATION_STYLES[s.relation] || RELATION_STYLES.default;",
    "      ctx.beginPath();",
    "      if (style.dash && ctx.setLineDash) ctx.setLineDash(style.dash);",
    "      ctx.moveTo(a.x, a.y);",
    "      ctx.lineTo(b.x, b.y);",
    "      ctx.strokeStyle = style.color;",
    "      // Ensure edge stroke is visible even when zoomed out",
    "      ctx.lineWidth = Math.max(0.8, style.width) / Math.max(zoom, 0.5);",
    "      ctx.globalAlpha = 0.95;",
    "      ctx.stroke();",
    "      if (ctx.setLineDash) ctx.setLineDash([]);",
    "    }",
    "",
    "    // Draw nodes from leaves inward so the project core reads as the visual anchor.",
    "    const tierPriority = { edge: 0, child: 1, god: 2, project: 3 };",
    "    const drawNodes = sim.slice().sort((a, b) => (tierPriority[a.tier] || 0) - (tierPriority[b.tier] || 0));",
    "    for (const n of drawNodes) {",
    "      const shell = NODE_SHELLS[n.tier] || NODE_SHELLS.edge;",
    "      const radius = nodeRadiusFor(n);",
    "      const fillColor = n.projectFill || projectFillColor(n.clusterRoot || n.id);",
    "      const outlineColor = n.outlineColor || scopeOutlineColor(n.memoryScope);",
    "      const shape = n.shape || tierShape(n.tier);",
    "      const isSelected = n.id === selectedId;",
    "      const isHovered = n.id === hoveredId;",
    "      const highlighted = isSelected || isHovered;",
    "",
    "      // Draw shape path",
    "      pathShape(ctx, n.x, n.y, radius, shape);",
    "      ctx.fillStyle = fillColor;",
    "      ctx.globalAlpha = isSelected ? 1.0 : shell.alpha;",
    "      ctx.fill();",
    "      ctx.globalAlpha = 1.0;",
    "      ctx.strokeStyle = isSelected ? \"#ffffff\" : isHovered ? \"#f59e0b\" : outlineColor;",
    "      ctx.lineWidth = ((n.tier === \"project\" ? 2.25 : n.tier === \"god\" ? 1.65 : n.tier === \"child\" ? 1.15 : 1.0) + (highlighted ? 0.35 : 0)) / zoom;",
    "      ctx.stroke();",
    "    }",
    "",
    "    // Labels: keep the graph readable by only showing the most important core nodes,",
    "    // plus any selected node. Dense graphs get a small label budget to avoid collisions.",
    "    ctx.globalAlpha = 1.0;",
    "    ctx.fillStyle = \"#e4e4e7\";",
    "    ctx.font = (11 / zoom) + \"px SF Mono, Monaco, monospace\";",
    "    ctx.textAlign = \"center\";",
    "    ctx.textBaseline = \"top\";",
    "",
    "    const labelBudget = sim.length > 30 ? 6 : sim.length > 15 ? 10 : 18;",
    "    const labelNodes = drawNodes",
    "      .filter((n) => n.tier === \"project\" || n.tier === \"god\")",
    "      .sort((a, b) => {",
    "        const degreeA = degreeMap.get(a.id) || 0;",
    "        const degreeB = degreeMap.get(b.id) || 0;",
    "        const scoreA = (a.tier === \"project\" ? 200 : 120) + degreeA * 10 + (a.isGod ? 40 : 0);",
    "        const scoreB = (b.tier === \"project\" ? 200 : 120) + degreeB * 10 + (b.isGod ? 40 : 0);",
    "        return scoreB - scoreA || a.id.localeCompare(b.id);",
    "      })",
    "      .slice(0, labelBudget);",
    "    const labelSet = new Set(labelNodes.map((n) => n.id));",
    "",
    "    for (const n of drawNodes) {",
    "      if (n.id === selectedId || labelSet.has(n.id)) {",
    "        const label = n.label.length > 30 ? n.label.slice(0, 27) + \"...\" : n.label;",
    "        ctx.fillText(label, n.x, n.y + 10);",
    "      }",
    "    }",
    "",
    "    ctx.restore();",
    "    syncViewState();",
    "    try {",
    "      if (selectedId) {",
    "        const pinnedNode = nodeById.get(selectedId);",
    "        if (pinnedNode) showTooltip(pinnedNode);",
    "      }",
    "    } catch {}",
    "    try {",
    "      layoutState.positions = new Map(sim.map((n) => [n.id, { x: n.x, y: n.y, tier: n.tier, seenBefore: !!n.seenBefore }]));",
    "      layoutState.seenIds = new Set(sim.map((n) => n.id));",
    "      window.__engram_graph_layoutState = layoutState;",
    "    } catch (e) {}",
    "    if (!perfRecorded) {",
    "      perfRecorded = true;",
    "      const totalMs = perfNow() - totalStart;",
    "      const sampleCount = (perfState.sampleCount || 0) + 1;",
    "      const alpha = sampleCount < 5 ? 0.5 : 0.18;",
    "      perfState.sampleCount = sampleCount;",
    "      perfState.avgTotalMs = perfState.avgTotalMs ? perfState.avgTotalMs * (1 - alpha) + totalMs * alpha : totalMs;",
    "      perfState.avgLayoutMs = perfState.avgLayoutMs ? perfState.avgLayoutMs * (1 - alpha) + layoutDuration * alpha : layoutDuration;",
    "      perfState.maxTotalMs = Math.max(perfState.maxTotalMs || 0, totalMs);",
    "      perfState.maxLayoutMs = Math.max(perfState.maxLayoutMs || 0, layoutDuration);",
    "      perfState.lastNodeCount = sim.length;",
    "      perfState.lastEdgeCount = springs.length;",
    "      if (layoutDuration > 24 || totalMs > 32) perfState.slowFrames = (perfState.slowFrames || 0) + 1;",
    "      window.__engram_graph_perfMetrics = perfState;",
    "    }",
    "  }",
    "",
    "  // \u2500\u2500\u2500 Animation loop \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
    "  let frames = 0;",
    "  let running = true;",
    "",
    "  // Expose a stop handle so subsequent renders can cleanly terminate",
    "  const stop = () => { running = false; };",
    "  window.__engram_graph_stop = stop;",
    "",
    "  function tick() {",
    "    if (!running) return;",
    "    // Stream mode gets one extra pump frame so the auto-fit settles; otherwise draw once and stop.",
    "    draw();",
    "    frames++;",
    "    if (layoutMode === 'stream' && frames < 2) {",
    "      requestAnimationFrame(tick);",
    "    } else {",
    "      running = false;",
    "    }",
    "  }",
    "  tick();",
    "",
    "  // \u2500\u2500\u2500 Interaction: pan + selection \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
    "  canvas.addEventListener(\"mousedown\", (e) => {",
    "    const x = e.offsetX;",
    "    const y = e.offsetY;",
    "",
    "    // Hit test for node click (world coords)",
    "    const worldX = (x - viewX) / zoom;",
    "    const worldY = (y - viewY) / zoom;",
    "    const clickedNode = pickNodeAt(worldX, worldY);",
    "",
    "    if (clickedNode) {",
    "      selectedId = clickedNode.id;",
    "      selectedEdge = null;",
    "      hoveredId = clickedNode.id;",
    "      const info = document.getElementById(\"graph-info\");",
    "      if (info) {",
    "        info.textContent = (clickedNode.tier || \"edge\") + \" · scope \" + (clickedNode.memoryScope || \"project\") + \" · \" + clickedNode.kind + \" · \" + clickedNode.label + (clickedNode.isGod ? \" (god node)\" : \"\");",
    "      }",
    "      const rect = canvas.getBoundingClientRect();",
    "      showTooltip(clickedNode, e.clientX ?? (rect.left + x), e.clientY ?? (rect.top + y));",
    "      try { canvas.focus({ preventScroll: true }); } catch {}",
    "    } else {",
    "      // If no node clicked, attempt an edge hit-test (pick the nearest segment)",
    "      let clickedEdge = null;",
    "      let bestDist = Infinity;",
    "      for (const s of springs) {",
    "        // distance from point to segment AB",
    "        const ax = s.a.x, ay = s.a.y, bx = s.b.x, by = s.b.y;",
    "        const px = worldX, py = worldY;",
    "        const dx = bx - ax, dy = by - ay;",
    "        const l2 = dx * dx + dy * dy;",
    "        let t = 0;",
    "        if (l2 > 0) t = ((px - ax) * dx + (py - ay) * dy) / l2;",
    "        t = Math.max(0, Math.min(1, t));",
    "        const projx = ax + t * dx, projy = ay + t * dy;",
    "        const dist2 = (projx - px) * (projx - px) + (projy - py) * (projy - py);",
    "        if (dist2 < bestDist) {",
    "          bestDist = dist2;",
    "          clickedEdge = s;",
    "        }",
    "      }",
    "      // threshold in world coords (approx)",
    "      if (clickedEdge && bestDist < (12 * 12)) {",
    "        selectedEdge = clickedEdge;",
    "        selectedId = null;",
    "        hoveredId = null;",
    "        hideTooltip();",
    "        const info = document.getElementById(\"graph-info\");",
    "        if (info) {",
    "          info.textContent = (selectedEdge.relation || 'edge') + ' \u00b7 ' + selectedEdge.a.label + ' \u2194 ' + selectedEdge.b.label;",
    "        }",
    "      } else {",
    "        // Start panning",
    "        draggingView = true;",
    "        dragStartX = x - viewX;",
    "        dragStartY = y - viewY;",
    "        selectedId = null;",
    "        selectedEdge = null;",
    "        hoveredId = null;",
    "        hideTooltip();",
    "      }",
    "    }",
    "    draw();",
    "  });",
    "",
    "  canvas.addEventListener(\"mousemove\", (e) => {",
    "    lastMouseX = e.offsetX;",
    "    lastMouseY = e.offsetY;",
    "    const rect = canvas.getBoundingClientRect();",
    "    if (draggingView) {",
    "      viewX = e.offsetX - dragStartX;",
    "      viewY = e.offsetY - dragStartY;",
    "      hoveredId = null;",
    "      canvas.style.cursor = \"grabbing\";",
    "      const pinnedNode = selectedId ? nodeById.get(selectedId) : null;",
    "      if (pinnedNode) showTooltip(pinnedNode); else hideTooltip();",
    "      draw();",
    "      return;",
    "    }",
    "    const worldX = (e.offsetX - viewX) / zoom;",
    "    const worldY = (e.offsetY - viewY) / zoom;",
    "    const hoveredNode = pickNodeAt(worldX, worldY);",
    "    hoveredId = hoveredNode ? hoveredNode.id : null;",
    "    canvas.style.cursor = hoveredNode ? \"pointer\" : \"grab\";",
    "    if (hoveredNode) {",
    "      showTooltip(hoveredNode, e.clientX ?? (rect.left + e.offsetX), e.clientY ?? (rect.top + e.offsetY));",
    "    } else if (selectedId) {",
    "      const pinnedNode = nodeById.get(selectedId);",
    "      if (pinnedNode) showTooltip(pinnedNode); else hideTooltip();",
    "    } else {",
    "      hideTooltip();",
    "    }",
    "    draw();",
    "  });",
    "",
    "  canvas.addEventListener(\"mouseup\", () => { draggingView = false; });",
    "  canvas.addEventListener(\"mouseleave\", () => {",
    "    draggingView = false;",
    "    hoveredId = null;",
    "    if (selectedId) {",
    "      const pinnedNode = nodeById.get(selectedId);",
    "      if (pinnedNode) showTooltip(pinnedNode);",
    "    } else {",
    "      hideTooltip();",
    "    }",
    "    canvas.style.cursor = \"grab\";",
    "  });",
    "",
    "  // \u2500\u2500\u2500 Interaction: zoom (wheel + keyboard) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
    "  canvas.addEventListener(\"wheel\", (e) => {",
    "    e.preventDefault();",
    "    const zoomDelta = e.deltaY > 0 ? 0.9 : 1.1;",
    "    const newZoom = Math.max(0.2, Math.min(3, zoom * zoomDelta));",
    "",
    "    // Anchor zoom on cursor",
    "    const mx = e.offsetX;",
    "    const my = e.offsetY;",
    "    viewX = mx - ((mx - viewX) * newZoom) / zoom;",
    "    viewY = my - ((my - viewY) * newZoom) / zoom;",
    "    zoom = newZoom;",
    "    draw();",
    "  }, { passive: false });",
    "",
    "  // Keyboard zoom: - / = keys. Center on selected node/edge if any, else on",
    "  // the last mouse cursor position.",
    "  function keyboardZoom(zoomDelta) {",
    "    const newZoom = Math.max(0.2, Math.min(3, zoom * zoomDelta));",
    "    let targetX = null;",
    "    let targetY = null;",
    "    if (selectedId) {",
    "      const n = nodeById.get(selectedId);",
    "      if (n) {",
    "        // center selected node in viewport at newZoom",
    "        targetX = (W / 2) - (n.x * newZoom);",
    "        targetY = (H / 2) - (n.y * newZoom);",
    "      }",
    "    } else if (selectedEdge) {",
    "      const a = selectedEdge.a, b = selectedEdge.b;",
    "      const cx = (a.x + b.x) / 2;",
    "      const cy = (a.y + b.y) / 2;",
    "      targetX = (W / 2) - (cx * newZoom);",
    "      targetY = (H / 2) - (cy * newZoom);",
    "    } else if (lastMouseX != null && lastMouseY != null) {",
    "      const mx = lastMouseX;",
    "      const my = lastMouseY;",
    "      targetX = mx - ((mx - viewX) * newZoom) / zoom;",
    "      targetY = my - ((my - viewY) * newZoom) / zoom;",
    "    } else {",
    "      targetX = (W / 2) - ((W / 2 - viewX) * newZoom) / zoom;",
    "      targetY = (H / 2) - ((H / 2 - viewY) * newZoom) / zoom;",
    "    }",
    "    viewX = targetX;",
    "    viewY = targetY;",
    "    zoom = newZoom;",
    "    draw();",
    "  }",
    "",
    "  if (window.__engram_graph_keydownHandler) {",
    "    try { window.removeEventListener('keydown', window.__engram_graph_keydownHandler, true); } catch {}",
    "  }",
    "  const keydownHandler = (ev) => {",
    "    if (ev.ctrlKey || ev.metaKey || ev.altKey) return;",
    "    const key = ev.key || '';",
    "    const code = ev.code || '';",
    "    const isZoomOut = key === '-' || key === '_' || code === 'Minus' || code === 'NumpadSubtract';",
    "    const isZoomIn = key === '=' || key === '+' || code === 'Equal' || code === 'NumpadAdd';",
    "    if (isZoomOut || isZoomIn) {",
    "      ev.preventDefault();",
    "      ev.stopPropagation();",
    "      if (typeof ev.stopImmediatePropagation === 'function') ev.stopImmediatePropagation();",
    "      keyboardZoom(isZoomOut ? 0.9 : 1.1);",
    "    }",
    "  };",
    "  window.__engram_graph_keydownHandler = keydownHandler;",
    "  window.addEventListener('keydown', keydownHandler, true);",
    "  try { canvas.addEventListener('keydown', keydownHandler); } catch {}",
    "}",
    "",
    "  async function renderGraphPriorityStream(canvas, nodes, godNodes, edges) {",
    "    const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));",
    "    const streamToken = (window.__engram_graph_streamToken || 0) + 1;",
    "    window.__engram_graph_streamToken = streamToken;",
    "    const isCurrent = () => window.__engram_graph_streamToken === streamToken;",
    "    const streamStart = Date.now();",
    "    window.__engram_graph_autoFit = true;",
    "",
    "    const safeNodes = Array.isArray(nodes) ? nodes.slice() : [];",
    "    const safeEdges = Array.isArray(edges) ? edges.slice() : [];",
    "    const godEntries = Array.isArray(godNodes) ? godNodes.slice() : [];",
    "    const godList = godEntries.map((g) => (g && g.node) ? g.node : g).filter(Boolean);",
    "",
    "    const degreeMap = new Map();",
    "    const adjacency = new Map();",
    "    const incidentEdges = new Map();",
    "    const projectRootOf = (n) => {",
    "      const md = n && n.metadata ? n.metadata : {};",
    "      return md.projectRoot || md.project_root || '__no_project__';",
    "    };",
    "    const memoryScopeOf = (n) => {",
    "      const md = n && n.metadata ? n.metadata : {};",
    "      return md.memoryScope || md.memory_scope || 'project';",
    "    };",
    "    const addAdj = (a, b) => {",
    "      if (!a || !b) return;",
    "      const listA = adjacency.get(a) || [];",
    "      if (!listA.includes(b)) {",
    "        listA.push(b);",
    "        adjacency.set(a, listA);",
    "      }",
    "      const listB = adjacency.get(b) || [];",
    "      if (!listB.includes(a)) {",
    "        listB.push(a);",
    "        adjacency.set(b, listB);",
    "      }",
    "    };",
    "    const addIncident = (id, edge) => {",
    "      const list = incidentEdges.get(id) || [];",
    "      list.push(edge);",
    "      incidentEdges.set(id, list);",
    "    };",
    "",
    "    for (const e of safeEdges) {",
    "      degreeMap.set(e.source, (degreeMap.get(e.source) || 0) + 1);",
    "      degreeMap.set(e.target, (degreeMap.get(e.target) || 0) + 1);",
    "      addAdj(e.source, e.target);",
    "      addIncident(e.source, e);",
    "      addIncident(e.target, e);",
    "    }",
    "",
    "    const godIdSet = new Set(godList.map((n) => n.id));",
    "    const nodePriority = (n) => {",
    "      const degree = degreeMap.get(n.id) || 0;",
    "      const kind = n.kind || 'default';",
    "      let score = degree * 10;",
    "      if (kind === 'file' || kind === 'module') score += 120;",
    "      if (kind === 'function' || kind === 'class' || kind === 'method') score += 60;",
    "      if (kind === 'concept') score += 25;",
    "      if (kind === 'mistake' || kind === 'decision') score += 35;",
    "      if (memoryScopeOf(n) === 'project') score += 30;",
    "      if (memoryScopeOf(n) === 'global') score += 15;",
    "      if (godIdSet.has(n.id)) score += 150;",
    "      return score;",
    "    };",
    "    const sortUnique = (items) => {",
    "      const seen = new Set();",
    "      return (items || [])",
    "        .filter((n) => n && n.id && !seen.has(n.id) && (seen.add(n.id), true))",
    "        .sort((a, b) => nodePriority(b) - nodePriority(a) || a.id.localeCompare(b.id));",
    "    };",
    "",
    "    const groups = new Map();",
    "    for (const n of safeNodes) {",
    "      const root = projectRootOf(n);",
    "      const arr = groups.get(root) || [];",
    "      arr.push(n);",
    "      groups.set(root, arr);",
    "    }",
    "",
    "    const masters = [];",
    "    for (const [, list] of groups.entries()) {",
    "      const candidates = sortUnique(list);",
    "      if (candidates.length) masters.push(candidates[0]);",
    "    }",
    "    if (masters.length === 0) masters.push(...sortUnique(godList).slice(0, Math.min(8, godList.length)));",
    "    if (masters.length === 0) masters.push(...sortUnique(safeNodes).slice(0, Math.min(4, safeNodes.length)));",
    "",
    "    const masterIds = new Set(masters.map((n) => n.id));",
    "    const dist = new Map();",
    "    const queue = [];",
    "    for (const m of masters) {",
    "      if (!m || !m.id) continue;",
    "      dist.set(m.id, 0);",
    "      queue.push(m.id);",
    "    }",
    "    while (queue.length > 0) {",
    "      const id = queue.shift();",
    "      const next = adjacency.get(id) || [];",
    "      const base = dist.get(id) || 0;",
    "      for (const neighbor of next) {",
    "        if (!dist.has(neighbor)) {",
    "          dist.set(neighbor, base + 1);",
    "          queue.push(neighbor);",
    "        }",
    "      }",
    "    }",
    "",
    "    const rounds = [];",
    "    const unreachable = [];",
    "    for (const n of safeNodes) {",
    "      if (masterIds.has(n.id)) continue;",
    "      const d = dist.get(n.id);",
    "      if (d == null) {",
    "        unreachable.push(n);",
    "        continue;",
    "      }",
    "      const idx = Math.max(0, d - 1);",
    "      if (!rounds[idx]) rounds[idx] = [];",
    "      rounds[idx].push(n);",
    "    }",
    "",
    "    const rankRoundNode = (n) => {",
    "      const degree = degreeMap.get(n.id) || 0;",
    "      const scope = memoryScopeOf(n);",
    "      const kind = n.kind || 'default';",
    "      let score = degree * 10;",
    "      if (projectRootOf(n) !== '__no_project__') score += 15;",
    "      if (scope === 'project') score += 30;",
    "      if (scope === 'global') score += 15;",
    "      if (scope === 'entity' || scope === 'personal') score += 5;",
    "      if (godIdSet.has(n.id)) score += 150;",
    "      if (kind === 'file' || kind === 'module') score += 80;",
    "      if (kind === 'function' || kind === 'class' || kind === 'method') score += 40;",
    "      return score;",
    "    };",
    "    const sortRound = (arr) => (arr || []).slice().sort((a, b) => rankRoundNode(b) - rankRoundNode(a) || a.id.localeCompare(b.id));",
    "",
    "    const visibleNodes = [];",
    "    const visibleIds = new Set();",
    "    const visibleEdges = [];",
    "    const visibleEdgeKeys = new Set();",
    "",
    "    const addNode = (node) => {",
    "      if (!node || !node.id || visibleIds.has(node.id)) return false;",
    "      visibleIds.add(node.id);",
    "      visibleNodes.push(node);",
    "      return true;",
    "    };",
    "    const addEdgesFor = (nodeId) => {",
    "      const list = incidentEdges.get(nodeId) || [];",
    "      for (const e of list) {",
    "        if (!visibleIds.has(e.source) || !visibleIds.has(e.target)) continue;",
    "        const key = e.source + '->' + e.target + '|' + (e.relation || 'default');",
    "        if (visibleEdgeKeys.has(key)) continue;",
    "        visibleEdgeKeys.add(key);",
    "        visibleEdges.push(e);",
    "      }",
    "    };",
    "",
    "    const renderCurrent = (mode, scale = 1) => {",
    "      if (!isCurrent()) return null;",
    "      window.__engram_graph_layoutMode = mode;",
    "      window.__engram_graph_layoutScale = mode === 'stream' ? 1 : scale;",
    "      renderGraph(canvas, visibleNodes.slice(), godEntries, visibleEdges.slice());",
    "      const metrics = window.__engram_graph_layoutMetrics || null;",
    "      try {",
    "        renderMemoryLegend(visibleNodes.slice(), visibleEdges.slice(), safeNodes.length);",
    "      } catch (e) {",
    "        // ignore legend failures during progressive streaming",
    "      }",
    "      return metrics;",
    "    };",
    "    const updateInfo = (metrics, stage) => {",
    "      if (!isCurrent()) return;",
    "      const overlapText = metrics && typeof metrics.overlapCount === 'number' ? ' \u00b7 overlaps ' + metrics.overlapCount : '';",
    "      const shellText = metrics && typeof metrics.meanShellError === 'number' ? ' \u00b7 shell ' + metrics.meanShellError.toFixed(2) : '';",
    "      if (typeof setText === 'function') setText('graph-info', visibleNodes.length + ' streamed / ' + safeNodes.length + ' nodes \u2014 ' + stage + overlapText + shellText);",
    "    };",
    "    const settleVisible = async (stage, baseScale) => {",
    "      let metrics = renderCurrent('stream', baseScale);",
    "      updateInfo(metrics, stage);",
    "      if (!isCurrent()) return { metrics: null, scale: baseScale };",
    "      await sleep(10);",
    "      if (metrics && metrics.overlapCount > 0) {",
    "        metrics = renderCurrent('stream', baseScale);",
    "        updateInfo(metrics, stage + ' fix');",
    "        await sleep(10);",
    "      }",
    "      return { metrics, scale: baseScale };",
    "    };",
    "",
    "    const batchPressure = () => {",
    "      const perf = window.__engram_graph_perfMetrics || {};",
    "      return Math.max(Number(perf.avgStreamMs || perf.avgTotalMs || 0), Number(perf.avgLayoutMs || 0));",
    "    };",
    "    const batchSizeForPressure = () => {",
    "      const pressure = batchPressure();",
    "      if (pressure > 120) return 6;",
    "      if (pressure > 60) return 4;",
    "      if (pressure > 25) return 2;",
    "      return 1;",
    "    };",
    "    let batchSize = batchSizeForPressure();",
    "    let pendingCount = 0;",
    "    let pendingScale = 1;",
    "    let pendingStage = \"\";",
    "    const flushBatch = async (stage, baseScale) => {",
    "      if (pendingCount === 0) return { metrics: null, scale: baseScale };",
    "      const settled = await settleVisible(stage, baseScale);",
    "      pendingCount = 0;",
    "      pendingStage = \"\";",
    "      batchSize = batchSizeForPressure();",
    "      return settled;",
    "    };",
    "    const queueNode = async (node, stageLabel, currentScale) => {",
    "      if (!isCurrent()) return currentScale;",
    "      if (!addNode(node)) return currentScale;",
    "      addEdgesFor(node.id);",
    "      pendingCount++;",
    "      pendingScale = currentScale;",
    "      pendingStage = stageLabel;",
    "      await sleep(10);",
    "      if (pendingCount >= batchSize) {",
    "        const settled = await flushBatch(pendingStage, pendingScale);",
    "        return Math.max(currentScale, settled.scale);",
    "      }",
    "      return currentScale;",
    "    };",
    "    let scale = 1;",
    "    for (const master of sortRound(masters)) {",
    "      if (!isCurrent()) return;",
    "      scale = await queueNode(master, 'master ' + (master.label || master.id), scale);",
    "    }",
    "    if (pendingCount > 0) {",
    "      const settled = await flushBatch(pendingStage || 'master batch', scale);",
    "      scale = Math.max(scale, settled.scale);",
    "    }",
    "    const masterSeal = await settleVisible('master seal', scale);",
    "    scale = Math.max(scale, masterSeal.scale);",
    "",
    "    for (let roundIndex = 0; roundIndex < rounds.length; roundIndex++) {",
    "      const round = sortRound(rounds[roundIndex]);",
    "      for (const node of round) {",
    "        if (!isCurrent()) return;",
    "        scale = await queueNode(node, 'round ' + (roundIndex + 1) + '/' + rounds.length, scale);",
    "      }",
    "      if (pendingCount > 0) {",
    "        const settled = await flushBatch(pendingStage || ('round ' + (roundIndex + 1) + ' batch'), scale);",
    "        scale = Math.max(scale, settled.scale);",
    "      }",
    "      const seal = await settleVisible('round ' + (roundIndex + 1) + '/' + rounds.length + ' seal', scale);",
    "      scale = Math.max(scale, seal.scale);",
    "    }",
    "",
    "    if (unreachable.length) {",
    "      const orphanRound = sortRound(unreachable);",
    "      for (const node of orphanRound) {",
    "        if (!isCurrent()) return;",
    "        scale = await queueNode(node, 'orphan cluster', scale);",
    "      }",
    "      if (pendingCount > 0) {",
    "        const settled = await flushBatch(pendingStage || 'orphan batch', scale);",
    "        scale = Math.max(scale, settled.scale);",
    "      }",
    "      const orphanSeal = await settleVisible('orphan seal', scale);",
    "      scale = Math.max(scale, orphanSeal.scale);",
    "    }",
    "",
    "    const streamTotalMs = Date.now() - streamStart;",
    "    const streamPerf = window.__engram_graph_perfMetrics || (window.__engram_graph_perfMetrics = {});",
    "    const streamSamples = (streamPerf.streamSampleCount || 0) + 1;",
    "    const streamAlpha = streamSamples < 5 ? 0.5 : 0.2;",
    "    streamPerf.streamSampleCount = streamSamples;",
    "    streamPerf.avgStreamMs = streamPerf.avgStreamMs ? streamPerf.avgStreamMs * (1 - streamAlpha) + streamTotalMs * streamAlpha : streamTotalMs;",
    "    streamPerf.maxStreamMs = Math.max(streamPerf.maxStreamMs || 0, streamTotalMs);",
    "    streamPerf.lastStreamNodes = visibleNodes.length;",
    "    streamPerf.lastSourceNodes = safeNodes.length;",
    "    streamPerf.lastVisibleEdges = visibleEdges.length;",
    "    streamPerf.lastBatchSize = batchSize;",
    "    streamPerf.lastRounds = rounds.length + (unreachable.length ? 1 : 0);",
    "    window.__engram_graph_perfMetrics = streamPerf;",
    "    window.__engram_graph_autoFit = false;",
    "  }",
    "",
    "  window.__engram_graph_renderGraphPriorityStream = renderGraphPriorityStream;",
    ""
  ].join("\n");
}
